[package]
name = "project-euler"
version = "0.1.0"
authors = ["Jay Rovacsek"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "1.1"
rayon = "1.1"
rand = "0.7.2"
primes = "0.3.0"